version: "3.8"
services:
  dreamscape-backend:
    build:
      # Dockerfile이 있는 폴더 경로를 정확히 지정하세요!
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # 예시 포트
    depends_on:
      - mysql # DB가 실행된 후 백엔드 실행
    environment:
      - DB_HOST=mysql
      # 필요한 환경변수 추가...

  mysql:
    image: mysql:8
    container_name: dream-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dream_db
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: dream-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dream_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
