spring.application.name=dreamScape

# OpenAI Configuration
openai.api.key=test
openai.model=gpt-4o
openai.api-url=https://api.openai.com/v1/chat/completions
openai.temperature=0.3
openai.max-tokens=500
openai.n=1

# Hailuo Configuration
hailuo.api.key=test
hailuo.api-key=test
hailuo.api-url=https://api.minimax.io/v1/

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=test
spring.security.oauth2.client.registration.google.client-secret=test
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/dream_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Seanshine18@

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

# Static resources
spring.web.resources.static-locations=file:uploads/

# Security logging
logging.level.org.springframework.security=DEBUG

# data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true