spring.application.name=dreamScape

# OpenAI Configuration
# OpenAI
openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o
openai.api-url=https://api.openai.com/v1/chat/completions
openai.temperature=0.3 
openai.max-tokens=500
openai.n=1


# Hailuo Configuration
hailuo.api.key=${HAILUO_API_KEY}
hailuo.api-url=https://api.minimax.io/v1/

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# Database
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/dream_db
spring.datasource.username=root
spring.datasource.password=jin@123

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Static resources
spring.web.resources.static-locations=file:uploads/

# Security logging
logging.level.org.springframework.security=DEBUG

# data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true